# I use the latest Docker-Compose version (3.8) and I have Docker 20.10 as an engine
version: "3.8"

# Next all the containers
services:

  db:
    image: mongo
    # restart policy is set to restart, unless stopped by the user
    restart: unless-stopped
    ports:
      - 27017:27017
    env_file: .env
    volumes:
      - ./mongodb/database:/data/db

  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
    image: lnk3/be:v1
    ports:
      - "8081:80"
    container_name: dart_backend
    volumes:
      - ./backend/:/app
    links:
      - db
    depends_on:
      - db