# I use the latest Docker-Compose version (3.8) and I have Docker 20.10 as an engine
version: "3.8"

# Next all the containers
services:

  db:
    image: mongo:3.6
    # restart policy is set to restart, unless stopped by the user
    restart: unless-stopped
    ports:
      - 27017:27017
    env_file: .db.env
    volumes:
      - ./mongodb/database:/data/db

  backend:
    # build:
    #   context: backend/
    #   dockerfile: Dockerfile
    # image: lnk3/be:v1
    image: google/dart
    volumes:
      - ./backend:/backend
    env_file:
      - .be.env
      - .db.env
    ports:
      - "8081:80"
    working_dir: /backend/
     # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      - db