name: backend
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  #  path: ^1.7.0
  shelf: ^1.2.0
  shelf_router: ^1.1.0
  mongo_dart: ^0.7.0+2
  intl: ^0.17.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
